### PR TITLE
Adding support for the 4x4 RGB LED matrix of Keybow 2040

### PR DESCRIPTION
**Pull request by sandyjmacdonald**
This adds support for x, y addressing of Keybow 2040's RGB LED keys, in a similar way to the LED SHIM in this library.

Keybow 2040 is an RP2040-powered mini mechanical keyboard with a 4x4 grid of keys (wired straight to GPIO pins of the RP2040) and 16 RGB LEDs driven by the IS31FL3731 driver chip.

The code added here was tested against the [CircuitPython 6.1.0](https://github.com/adafruit/circuitpython/releases/tag/6.1.0) release.

### CODE REVIEW

**Comment by sandyjmacdonald** [comment]
Well, I haven't the foggiest as to why those checks failed...

**Comment by ladyada** [comment]
looks like you need to run `black`

https://learn.adafruit.com/improve-your-code-with-pylint

**Comment by sandyjmacdonald** [comment]
> looks like you need to run `black`
> 
> https://learn.adafruit.com/improve-your-code-with-pylint

Thanks, Limor! On it.

**Review by makermelissa — APPROVED** [review]
Thank you for adding.

**Pull request merged**
