### PR TITLE
5x5 breakout

### PR DESCRIPTION
**Pull request by dglaude**
This is not tested on the real hardware, so it has to be considered draft until this is tested.

Room for improvement:

- lookup table is the one from Pimoroni library, it has 3 unused entries (28 vs 25) but that is the same as upstream: https://github.com/pimoroni/rgbmatrix5x5-python/blob/7eed75c57604b2c8afc0bcb82ff0221f0ecbbd3f/library/rgbmatrix5x5/is31fl3731.py#L367
- lookup table can be replaced by computation as it was done in led_shim.py (memory vs cpu tradeof): https://github.com/adafruit/Adafruit_CircuitPython_IS31FL3731/blob/11533d4827249ca33e8b9d5840f272494606688b/adafruit_is31fl3731/led_shim.py#L63

### CODE REVIEW

**Comment by dglaude** [comment]
Ok, and pylint believe there is duplicate code because Keybow 2040 use a very similar lookup table (even if it only contain 16 entries and at least 4 entries do not exist in led-shim/matrix5x5 table.

**Review by ladyada — APPROVED** [review]

**Comment by tannewt** [comment]
> Ok, and pylint believe there is duplicate code because Keybow 2040 use a very similar lookup table (even if it only contain 16 entries and at least 4 entries do not exist in led-shim/matrix5x5 table.

I think the duplication is coming from `pixelrgb` instead of the lookup. I think you can create a parent class for 5x5 and keybow that adds pixelrgb for both.

**Comment by jposada202020** [comment]
@dglaude :) would you be able to work on this?  thanks

**Comment by lesamouraipourpre** [comment]
Unfortunately, the current `pixel_addr` doesn't work for this led matrix. (Video below)
The test code is slightly modified from the example to repeat endlessly.
https://user-images.githubusercontent.com/70200140/121439010-f6486780-c97c-11eb-8339-a846aa2dbc24.mp4

If I have time this weekend I'll try to work out the correct values.

**Comment by lesamouraipourpre** [comment]
Hi @dglaude.

I believe I've got this working correctly and passing pre-commit:
https://user-images.githubusercontent.com/70200140/121524981-c6867780-c9ef-11eb-9e24-695349321be2.mp4

If you can give me write permission to this branch, I push a commit with the changes.

**Comment by tannewt** [comment]
Superseded by #45

**Pull request closed without merging**
